function m(b,a,c,d){b.j.pb(b.sb,a,c,d)}function n(b,a,c,d){b.j.ea?m(b,a,c,d):b.j.Te()._OnMessageFromDOM({type:"event",component:b.sb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.j.B(b.sb,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}function aa(b){b.$b||(b.j.Ec(b.je),b.$b=!0)}window.Ea=class{constructor(b,a){this.j=b;this.sb=a;this.$b=!1;this.je=()=>this.Sa()}td(){}Sa(){}};
window.Ef=class{constructor(){this.od=-1}l(){-1!==this.od&&(self.clearTimeout(this.od),this.od=-1)}};"use strict";class ca{constructor(b){this.vb=b;this.Vc=!1;this.bd=!0;this.xb=this.ra=this.pd=-1}}
function da(b,a){const c=a.elementId,d=b.uc(c,a),e=new ca(d);b.Ma.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.bd=!!a.isVisible;d.addEventListener("focus",()=>{ea(b,"elem-focused",c)});d.addEventListener("blur",()=>{ea(b,"elem-blurred",c)});const f=a.htmlIndex;e.pd=f;e.xb=a.htmlZIndex;b.Va&&(a=b.j.wc(f),e.ra=a,b.j.Nb(a).appendChild(d))}function w(b,a,c){q(b,a,d=>{const e=x(b,d.elementId);return c(e,d)})}
function x(b,a){b=b.Ma.get(a);if(!b)throw Error(`no element with id ${a}`);return b.vb}function ea(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function y(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.Mb=class extends self.Ea{constructor(b,a){super(b,a);this.Ma=new Map;this.Va=!0;r(this,[["create",c=>da(this,c)],["destroy",c=>{c=c.elementId;const d=x(this,c);this.Va&&d.parentElement.removeChild(d);this.Ma.delete(c)}],["set-visible",c=>{if(this.Va){var d=this.Ma.get(c.elementId),e=d.vb;d.Vc?e.style.display=c.isVisible?"":"none":d.bd=!!c.isVisible}}],["update-position",c=>{if(this.Va){var d=this.Ma.get(c.elementId),e=d.vb,f=this.j;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.pd=g;g=f.wc(g);g!==d.ra&&(e.remove(),f.Nb(g).appendChild(e),d.ra=g,f.Pc());c=c.htmlZIndex;c!==d.xb&&(d.xb=c,f.Pc());d.Vc||(d.Vc=!0,d.bd&&(e.style.display=""))}}],["update-state",c=>{const d=x(this,c.elementId);this.Rb(d,c)}],["focus",c=>this.Mc(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",
c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);w(this,"get-element",c=>c)}uc(){throw Error("required override");}Rb(){throw Error("required override");}Mc(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),ha=/android/i.test(navigator.userAgent);let ia=0;
function ja(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.uf?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.yf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ka(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let z=new Audio;
const la={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const oa=[];let A=0;window.RealFile=window.File;const B=[],pa=new Map,qa=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.ba=class b{constructor(a){this.ea=a.Af;this.Aa=null;this.aa="";this.fb=a.xf;this.Kb={};this.Za=this.wa=null;this.Xa=[];this.na=null;this.Xd=!0;this.M=[];this.hd=[];this.jd=!1;this.ke=()=>this.Re();this.Zc=!1;this.Rd=0;this.zb=null;this.eb=-1;this.qf=()=>this.bf();this.Hb=new Set;this.qd=null;this.le=[];this.u=a.me;this.ac="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ea=!1;if("cordova"===this.u&&this.ea&&ha){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ea=!1)}this.pa()?self.chrome.webview.addEventListener("message",c=>this.Hd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Hd(c));this.dc=this.ta=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.ff(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Xe());this.B("runtime","cordova-fetch-local-file",c=>this.Ye(c));this.B("runtime","create-job-worker",()=>this.Ze());this.B("runtime","send-wrapper-extension-message",c=>this.ef(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Sb(a)):this.Sb(a)}l(){this.Fc();this.Aa&&(this.Aa=this.Aa.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Za&&(this.Za.l(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}yd(){return this.M[0].canvas}wc(a){return Math.min(a,this.M.length-1)}Nb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}He(){return fa&&"cordova"===this.u}nb(){const a=navigator.userAgent;return fa&&ta.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Fe(){return ha}zd(){return ha&&ta.has(this.u)}Bd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}pa(){return this.Bd()||"xbox-uwp-webview2"===this.u}async Sb(a){this.ea&&!await ka()&&(this.ea=!1);"macos-wkwebview"===this.u?this.Ia({type:"ready"}):this.pa()&&(this.hf(),this.le=(await this.We()).registeredComponentIds);if("playable-ad"===this.u){this.ta=self.c3_base64files;this.dc={};await this.Oe();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.dc.hasOwnProperty(c)?a.hb[d]={uf:!0,yf:this.dc[c]}:this.ta.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.ta[c]))}a.sc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ec(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.wf?this.aa=a.wf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Cf&&(this.Kb=a.Cf);c=new MessageChannel;this.Aa=c.port1;this.Aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.af(d));this.zb=
new self.Ie(this);await xa(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ea?await this.Ve(a,c.port2):await this.Ue(a,c.port2)}Hc(a){a=this.Kb.hasOwnProperty(a)?this.Kb[a]:a.endsWith("/workermain.js")&&this.Kb.hasOwnProperty("workermain.js")?this.Kb["workermain.js"]:"playable-ad"===
this.u&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async vc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.ac)return a=await this.Lb(d.tf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}Fd(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ha(),g=window.devicePixelRatio,h=b.mb(),k=a.If,l=window.cr_previewImageBlobs||this.ta,p=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.me;var v=(new URLSearchParams(self.location.search)).has("debug"),C=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:v,ife:!!self.Hf,jobScheduler:{inputPort:C.Yc,outputPort:C.gd,maxNumWorkers:C.mf},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.ac,isiOSCordova:this.He(),isiOSWebView:this.nb(),isWindowsWebView2:this.Bd(),isAnyWebView2Wrapper:this.pa(),wrapperComponentIds:this.le,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ve(a,c){const d=this.Hc(a.Bf);"preview"===this.u?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const t=u=>{this.wa.removeEventListener("message",t);u.data&&"ok"===u.data.type?l():p()};this.wa.addEventListener("message",t);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.vc(d,this.aa,{type:"module",name:"Runtime",tf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.sc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,p=a.rc.length;l<p;++l){const t=
a.rc[l],u=t[0];if(u===a.rd||"scriptsInEvents.js"===u||u.endsWith("/scriptsInEvents.js"))t[1]=await this.Ta(u)}this.wa.postMessage(Object.assign(this.Fd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.rc,mainProjectScript:a.rd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ya(this.zb)]);this.Xa=B.map(l=>new l(this));this.Ed();za(e);Aa(g);Ba(this.na);self.c3_callFunction=(l,p)=>{var t=this.na;return t.j.Cd(t.sb,"js-invoke-function",
{name:l,params:p})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Ue(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Xa=B.map(h=>new h(this));this.Ed();za(d);Aa(e);e=a.hb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.sc)){var f=[...a.sc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>ja(h)));e=self.C3_ProjectScriptsStatus;f=a.rd;const g=a.rc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await ja(k),"preview"!==this.u||e[h]||this.Jd(h,"main script did not run to completion")}catch(l){this.Jd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ta(k),await ja(k);"preview"===this.u&&"object"!==typeof self.Df.Ff?(this.Ub(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Fd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:sa}),Ba(this.na),this.Gd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,
a))}Jd(a,c){this.Ub();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Gd(){this.Ub()}Ub(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ze(){const a=await Ca(this.zb);return{outputPort:a,transferables:[a]}}ff(a){if(!this.Zc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Xd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Xd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:p}=this.M.pop();p.remove();this.ea&&!d?this.hd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.ea?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,za(c),Aa(d),this.M.push({canvas:c,ib:d});for(const l of this.Xa)if(l instanceof window.Mb&&l.Va)for(const p of l.Ma.values())e=l.j.wc(p.pd),f=p.ra,-1!==e&&-1!==f&&e!==f&&(f=p.vb,f.remove(),l.j.Nb(e).appendChild(f),p.ra=e);this.Pc();return{addedCanvases:a,transferables:k}}Xe(){for(const a of this.hd)a.remove();this.hd.length=0}Pc(){this.jd||(this.jd=!0,this.Ec(this.ke))}Re(){this.Id(this.ke);
this.jd=!1;let a=[];for(var c of this.Xa)if(c instanceof window.Mb){var d=c.Va?[...c.Ma.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ra,l=h.ra;return k!==l?k-l:g.xb-h.xb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ra!==c&&(this.Dd(c,a.slice(d,e)),c=g.ra,d=e)}d<e&&this.Dd(c,a.slice(d,e))}Dd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.vb);var d=new Set(c);a=this.Nb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Te(){if(this.ea)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Cd(a,c,d,e,f){const g=ra++,h=new Promise((k,l)=>{qa.set(g,{resolve:k,reject:l})});this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.$e(a);if("result"===c)this.cf(a);else if("runtime-ready"===c)this.df();else if("alert-error"===c)this.Ub(),alert(a.message);else if("creating-runtime"===c)this.Gd();else throw Error(`unknown message '${c}'`);}$e(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=pa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Tb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Tb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Tb(f,!1,""+h)}):this.Tb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Tb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Aa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}cf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=qa.get(c);d?e.resolve(a):e.reject(a);qa.delete(c)}B(a,c,d){let e=pa.get(a);e||(e=new Map,pa.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static xa(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}Ed(){for(const a of this.Xa)if("runtime"===a.sb){this.na=a;return}throw Error("cannot find runtime DOM handler");}af(a){this.pb("debugger","message",a)}df(){for(const a of this.Xa)a.td()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static Vb(a){ua=!!a}Ec(a){this.Hb.add(a);
this.Oc()}Id(a){this.Hb.delete(a);0===this.Hb.size&&this.Fc()}Oc(){-1===this.eb&&0<this.Hb.size&&(this.eb=requestAnimationFrame(this.qf))}Fc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}bf(){this.eb=-1;for(const a of this.Hb)a();this.Oc()}Ha(a){this.na.Ha(a)}Ra(a){this.na.Ra(a)}Nc(){this.na.Nc()}Qb(a){this.na.Qb(a)}Ge(){return!!la["audio/webm; codecs=opus"]}async jf(a){a=await this.Cd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ke(a){this.Zc=!0;this.Rd=
a}Ee(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Ad(a){return!this.Ee(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.ac&&this.Ad(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Lb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ye(a){const c=a.filename;switch(a.as){case "text":return await this.De(c);case "buffer":return await this.Lb(c);default:throw Error("unsupported type");
}}wd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async De(a){a=await this.wd(a);return await ma(a)}Gc(){if(oa.length&&!(8<=A)){A++;var a=oa.shift();this.Pe(a.filename,a.zf,a.sf)}}Lb(a){return new Promise((c,d)=>{oa.push({filename:a,zf:e=>{A--;this.Gc();c(e)},sf:e=>{A--;this.Gc();d(e)}});this.Gc()})}async Pe(a,c,d){try{const e=await this.wd(a),f=await na(e);c(f)}catch(e){d(e)}}Hd(a){if("entered-fullscreen"===
a)b.Vb(!0),D(this.na);else if("exited-fullscreen"===a)b.Vb(!1),D(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.qd(a),this.qd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}ef(a){this.Ia({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ia(a){this.pa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}hf(){window.moveTo=(a,c)=>{this.Ia({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ia({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}We(){return this.pa()?new Promise(a=>{this.qd=a;this.Ia({type:"wrapper-init"})}):Promise.resolve()}async Oe(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Ne(c,d));
await Promise.all(a)}async Ne(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.dc[a]=c.str;else{let d=await this.Se(c);d||(d=this.Qe(c));this.ta[a]=d}}async Se(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Qe(a){a=this.gf(a);return this.Me(a.data,
a.vf)}gf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{vf:a,data:d}}Me(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const E=self.ba,Da=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Fa={dispatchUserScriptEvent:!0},Ga={dispatchRuntimeEvent:!0};function Ha(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ia(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function H(b){b=URL.createObjectURL(b);try{return await Ia(b)}finally{URL.revokeObjectURL(b)}}function Ja(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ka(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await H(b);var d=await Ja(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await H(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await H(b)}
function La(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ma=new Set(["input","textarea","datalist","select"]),Na=new Set(["canvas","body","html"]);function I(b){b.target.tagName&&Na.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Oa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Pa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await H(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ka(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Qa=!1;document.addEventListener("pause",()=>Qa=!0);document.addEventListener("resume",()=>Qa=!1);function za(b){b.addEventListener("selectstart",I);b.addEventListener("gesturehold",I);b.addEventListener("pointerdown",I)}function Aa(b){b.addEventListener("selectstart",Oa);b.addEventListener("gesturehold",Oa);b.addEventListener("touchstart",Oa)}function Ba(b){b.Qd=!0;b.cd=b.j.qa();b.Ab=b.j.ha()}
function D(b){if(!b.la){var a=E.mb();a&&"any"!==b.md&&Ra(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ha()})}}async function Sa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ta(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ua(b){return await self.C3_GetSvgImageSize(b.blob)}function Va(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Wa(b){self.setTimeout(()=>{b.Pd=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Xa(b,!0)),document.addEventListener("resume",()=>Xa(b,!1))):document.addEventListener("visibilitychange",()=>Xa(b,"hidden"===document.visibilityState));b.ic=!("hidden"!==document.visibilityState&&!Qa);return{isSuspended:b.ic}}
function Ya(b){b.Ld||(b.Ld=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Za(b){b.Kd||(b.Kd=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function $a(b){await Ha(b.url)}
function ab(b,a){b.Sd=a.message;-1===b.Tc&&(b.Tc=setTimeout(()=>{b.Tc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Sd)},250))}function bb(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:E.mb(),innerWidth:b.qa(),innerHeight:b.ha()})}
function Xa(b,a){b.ic!==a&&((b.ic=a)?b.j.Fc():b.j.Oc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function cb(b,a,c){"Backspace"===c.key&&I(c);if(b.j.pa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.la||(d=Da.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F))}
function J(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function K(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.ed);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},F);"mouse"===c.pointerType&&
(b.ed=c.buttons)}}function db(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Da=a))}}
function eb(b,a,c,d){const e=b.qa(),f=b.ha();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.mb()}):10>d&&fb(b,e,f,d+1)}function fb(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>eb(b,a,c,d),48)}
function Ra(b){b=b.md;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function gb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.xa(class extends self.Ea{constructor(b){super(b,"runtime");this.Qd=!1;this.gb=-1;this.md="any";this.ic=this.Kd=this.Ld=!1;this.oc=document.createElement("div");this.oc.className="c3-screen-reader-text";this.oc.setAttribute("aria-live","polite");document.body.appendChild(this.oc);this.La=null;this.la=!1;this.Sd="";this.Tc=-1;this.Pd=!1;this.cd=b.qa();this.Ab=b.ha();this.Da=this.Jb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Sa(c));b.B("runtime","raster-svg-image",c=>Ta(c));b.B("runtime","get-svg-image-size",c=>Ua(c));b.B("runtime","set-target-orientation",c=>{this.md=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Va(c));b.B("runtime","go-to-script",c=>Va(c));b.B("runtime","before-start-ticking",()=>Wa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.La||(this.La=document.createElement("div"),this.La.id="inspectOutline",document.body.appendChild(this.La));var d=this.La;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.La&&(this.La.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ya(this));b.B("runtime","enable-device-motion",()=>Za(this));b.B("runtime","add-stylesheet",c=>$a(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Kc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.oc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.yd().style.display="";this.j.Ke(c.duration)});b.B("runtime","export-to-video-progress",c=>ab(this,c));b.B("runtime","exported-to-video",c=>{window.rf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.rf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
La(d)||c.preventDefault()});window.addEventListener("selectstart",I);window.addEventListener("gesturehold",I);window.addEventListener("touchstart",I,{passive:!1});window.addEventListener("pointerdown",I,{passive:!1});this.ed=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Pa,{passive:!1});window.addEventListener("wheel",Pa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Qd){var c=this.qa();var d=this.ha();if(this.j.zd()){if(this.Pd){if(this.cd===
c&&d<this.Ab){this.Jb=this.Ab-d;db(this,this.Ab,this.Jb);c=void 0;break a}0<this.Jb&&(this.Jb=0,db(this,d,this.Jb))}this.cd=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.mb()});this.j.nb()&&(-1!==this.gb&&clearTimeout(this.gb),eb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>D(this));window.addEventListener("webkitfullscreenchange",()=>D(this));window.addEventListener("mozfullscreenchange",()=>
D(this));window.addEventListener("fullscreenerror",c=>bb(this,c));window.addEventListener("webkitfullscreenerror",c=>bb(this,c));window.addEventListener("mozfullscreenerror",c=>bb(this,c));if(b.nb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):La(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.fc=new WeakSet;this.za=!1}td(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Ga)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Ga);this.ed=0});window.addEventListener("focusin",a=>{a=a.target;(Ma.has(a.tagName.toLowerCase())||La(a))&&m(this,"keyboard-blur",null,Ga)});window.addEventListener("keydown",a=>cb(this,"keydown",a));window.addEventListener("keyup",a=>cb(this,"keyup",a));window.addEventListener("mousedown",a=>J(this,"mousedown",a,Fa));window.addEventListener("mousemove",a=>J(this,"mousemove",a,Fa));window.addEventListener("mouseup",a=>J(this,"mouseup",a,Fa));window.addEventListener("dblclick",
a=>J(this,"dblclick",a,F));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Da,pageX:a.pageX,pageY:a.pageY+this.Da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();gb(a.target)&&document.activeElement&&!gb(document.activeElement)&&document.activeElement.blur();K(this,"pointerdown",a)});this.j.ea&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{K(this,"pointermove",a)}):window.addEventListener("pointermove",a=>K(this,"pointermove",a));window.addEventListener("pointerup",a=>K(this,"pointerup",a));window.addEventListener("pointercancel",a=>K(this,"pointercancel",a));const b=()=>this.Nc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.j.Fe()&&!this.j.zd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.j.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ha(){return this.j.ha()}Nc(){var b=[...this.$a];this.$a.clear();if(!this.za)for(const a of b)(b=a.play())&&b.catch(()=>{this.fc.has(a)||this.$a.add(a)})}Ha(b){if("function"!==
typeof b.play)throw Error("missing play function");this.fc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.fc.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.fc.add(b)}Qb(b){this.za=!!b}Kc(b){alert(b.message)}});"use strict";
async function xa(b){if(b.kf)throw Error("already initialised");b.kf=!0;var a=b.Ba.Hc(("playable-ad"===b.Ba.u?b.Ba.fb:"")+"dispatchworker.js");b.Sc=await b.Ba.vc(a,b.rb,{name:"DispatchWorker"});a=new MessageChannel;b.Yc=a.port1;b.Sc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.gd=await Ca(b)}function ya(b){return[b.Yc,b.gd]}
async function Ca(b){const a=b.Yd.length;var c=b.Ba.Hc(("playable-ad"===b.Ba.u?b.Ba.fb:"")+"jobworker.js");c=await b.Ba.vc(c,b.rb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Sc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Yd.push(c);return e.port1}
self.Ie=class{constructor(b){this.Ba=b;this.rb=b.aa;this.rb="preview"===b.u?this.rb+"workers/":this.rb+b.fb;this.mf=Math.min(navigator.hardwareConcurrency||2,16);this.Sc=null;this.Yd=[];this.gd=this.Yc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ba({Af:!1,Bf:"workermain.js",hb:["scripts/c3runtime.js"],rc:[],rd:"",xf:"scripts/",sc:[],me:"html5"}));"use strict";
self.ba.xa(class extends self.Ea{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.yd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function hb(b,a){a=a.type;let c=!0;0===a?c=await ib():1===a&&(c=await kb());m(b,"permission-result",{type:a,result:c})}async function ib(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function kb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ba.xa(class extends self.Ea{constructor(b){super(b,"touch");q(this,"request-permission",a=>hb(this,a))}});"use strict";
async function lb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.ba.xa(class extends self.Ea{constructor(b){super(b,"localstorage");r(this,[["init",()=>this.Sb()],["request-persistent",()=>lb()]])}async Sb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
function L(b){b.stopPropagation()}function mb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.ba.xa(class extends self.Mb{constructor(b){super(b,"text-input");w(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}uc(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",L);c.addEventListener("pointermove",L);c.addEventListener("pointerrawupdate",L);c.addEventListener("pointerup",L);c.addEventListener("mousedown",
L);c.addEventListener("mouseup",L);c.addEventListener("keydown",mb);c.addEventListener("keyup",mb);c.addEventListener("click",e=>{e.stopPropagation();y(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();y(this,"dblclick",b)});c.addEventListener("input",()=>ea(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Rb(c,a);return c}Rb(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function nb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}
function M(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const c of b){b=c.parentNode;var a=b.replaceChild;const d=document.createElement("script");d.text=c.text;const e=c.attributes;for(let f=0,g=e.length;f<g;++f){const h=e[f];d.setAttribute(h.name,h.value)}d.setAttribute("c3-executed","");a.call(b,d,c)}}function N(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}
function O(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.ba.xa(class extends self.Mb{constructor(b){super(b,"html-element");w(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)"html"===f?(k.innerHTML=e,M(k)):k.textContent=e;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set content: ",h),d=O(null)}}return d});w(this,"insert-content",(a,c)=>{{const e=c.str,f=c.type,g=c["at-end"]?"beforeend":"afterbegin",h=c.selector;c=c["is-all"];try{const k=
N(a,h,c);if(0===k.length)var d=O(null);else{for(const l of k)"html"===f?(l.insertAdjacentHTML(g,e),M(l)):l.insertAdjacentText(g,e);d=O(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=O(null)}}return d});w(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const g=N(a,f,c);if(0===g.length)var d=O(null);else{for(const h of g)e?nb(h):h.remove();d=O(a)}}catch(g){console.warn("[HTML element] Failed to remove content: ",g),d=O(null)}else nb(a),
d=O(a)}return d});w(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)for(const l of f)switch(e){case "add":k.classList.add(l);break;case "toggle":k.classList.toggle(l);break;case "remove":k.classList.remove(l)}d=O(a)}}catch(h){console.warn("[HTML element] Failed to set class: ",h),d=O(null)}}return d});w(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,g=c.value,
h=c.selector;c=c["is-all"];try{const k=N(a,h,c);if(0===k.length)var d=O(null);else{for(const l of k)switch(e){case "set":l.setAttribute(f,g);break;case "remove":l.removeAttribute(f)}d=O(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=O(null)}}return d});w(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=O(a)}}catch(h){console.warn("[HTML element] Failed to set style: ",h),d=O(null)}}return d});w(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});w(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,g=c.selector,h=c.insertAt;let k=a;if(g&&(k=a.querySelector(g),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);
c["class"]&&(d.className=c["class"]);0===h?k.prepend(d):1===h?k.append(d):k.replaceChildren?k.replaceChildren(d):(nb(k),k.append(d));a=O(a)}return a});w(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}uc(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===c)break;e=e.parentNode}y(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;y(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect="none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?(c.innerHTML=d,M(c)):c.textContent=d;y(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}Rb(b,a){b.innerHTML=a.html;M(b)}});"use strict";const ob=180/Math.PI;
async function pb(b,a){if(a.isiOSCordova||a.isSafari)b.kc=!0;b.nd=a.timeScaleMode;b.ce=["equalpower","HRTF","soundfield"][a.panningModel];b.Od=["linear","inverse","exponential"][a.distanceModel];b.de=a.refDistance;b.be=a.maxDistance;b.fe=a.rolloffFactor;if(b.j.Zc)b.kc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Rd)});else{var c={latencyHint:a.latencyHint};b.ie||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");qb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&qb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Wa=b.g.createGain();b.Wa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function rb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,t=a.stereoPan;let u=a.off;0<u&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),u=u-a.performanceTime/1E3+a.contextTime):u=u-performance.now()/1E3+b.g.currentTime);b.Zd=g.slice(0);sb(b,g);try{b.R=await tb(b,c,d,e,g,f);if(p){Q(b.R,!0);var v=b.R,C=p.innerAngle,va=p.outerAngle,wa=p.outerGain;if(v.yb){ub(v,p.x,p.y,p.z,p.angle);var G=self.jb.Le;v.ua[0]!==G(C)&&
(v.ua[0]=G(C),v.F.coneInnerAngle=G(C));v.ua[1]!==G(va)&&(v.ua[1]=G(va),v.F.coneOuterAngle=G(va));v.ua[2]!==wa&&(v.ua[2]=wa,v.F.coneOuterGain=wa)}p.hasOwnProperty("uid")&&(b.R.sa=p.uid)}else"number"===typeof t&&0!==t?(R(b.R,!0),vb(b.R,t)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,u)}catch(Ib){console.error("[Construct] Audio: error starting playback: ",Ib);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.sd--;0===d.sd&&(d.resolve(),b.Gb.delete(c))}aa(b)}
async function wb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await xb(b,c);for(const h of S(b,c))if(!h.ya){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Pa=d;h.Ya=g;h.he=a}T(b)}async function yb(b,a){const c=a.tags;a=a.rate;await xb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Ja())}async function zb(b,a){const c=a.tags;a=a.pos;await xb(b,c);for(const d of S(b,c))d.Bc(a)}
async function Ab(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await tb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Bb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function Cb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.se(b,...e);else if("delay"===c)d=new self.qe(b,...e);else if("convolution"===c){var g=d=new self.pe(b,f.ia,...e),h=a.bufferType;g.Md=a.bufferOriginalUrl;g.Nd=h}else if("flanger"===c)d=
new self.te(b,...e);else if("phaser"===c)d=new self.ve(b,...e);else if("gain"===c)d=new self.ue(b,...e);else if("stereopan"===c)d=new self.xe(b,...e);else if("tremolo"===c)d=new self.ye(b,...e);else if("ringmod"===c)d=new self.we(b,...e);else if("distortion"===c)d=new self.re(b,...e);else if("compressor"===c)d=new self.oe(b,...e);else if("analyser"===c)d=new self.ne(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Wd=l.length;d.ld=
h;l.push(d);Db(g,h)}Eb(b)}
async function Fb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Fa()&&1===c||!e.Fa()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ka.values())for(const g of f)g.l();b.ka.clear();b.pc=a.timeScale;b.Uc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.za=a.isSilent;b.j.Qb(b.za);b.ec=a.masterVolume;b.Wa.gain.value=
b.ec;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Cb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Gb(b,f,c)));T(b)}
async function Hb(b,a){try{const c=b.g.suspend(a.time);b.Vd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Jb(d)),b.Vd=!0);await c}catch(c){Jb(c)}}
function qb(b){b.Zb||(b.Xc=!1,window.addEventListener("pointerup",b.Ca,!0),window.addEventListener("touchend",b.Ca,!0),window.addEventListener("click",b.Ca,!0),window.addEventListener("keydown",b.Ca,!0),b.Zb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.lb()===c)return await Kb(g),g;if(f)return null;if(e&&(b.kc||b.Ud)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Fa()?g.l():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.ie;e&&f&&(b.Ud=!0);c=!e||b.kc||f?new self.Be(b,a,c,d,e,f):new self.ze(b,a,c,d,e);b.ja.push(c);await Kb(c);b.ae.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.ae.add(a));return c}
function Lb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Nb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.fa()}function Db(b,a){a=a.toLowerCase();let c=b.fa();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Ob(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Na&&b.dd===a&&(b.Na.disconnect(),b.Na.connect(c))}
function*Ob(b,a){if(a)for(const c of b.H)Lb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Pb(b,a,c){return c?b.j.jf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Qb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Lb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function tb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.tc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Qc?new self.Ae(a.v,a,e):new self.Ce(a.v,a,e);b.H.push(e);return e}
function sb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={sd:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.sd++}function xb(b,a){return(b=b.Gb.get((0===a.length?b.Zd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ua.size)aa(b);else for(const a of b.H)if(!a.I&&!a.O()){aa(b);break}}function Rb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Eb(b){b.$c||(b.$c=!0,Promise.resolve().then(()=>Sb(b)))}
function Sb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.$c=!1}
async function Gb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await tb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),vb(b,d));c.Play(k,l,p,0);a.isPlaying||c.ob();c.Jc(a)}}}function Jb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.Ea{constructor(b){super(b,"audio");this.Wa=this.g=null;this.Zb=this.Xc=!1;this.Ca=()=>{if(!this.Xc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Zb&&(this.Xc=!0,window.removeEventListener("pointerup",this.Ca,!0),window.removeEventListener("touchend",this.Ca,!0),window.removeEventListener("click",this.Ca,!0),window.removeEventListener("keydown",
this.Ca,!0),this.Zb=!1)}};this.ja=[];this.H=[];this.R=null;this.Zd=[];this.ae=new Set;this.$d=-1;this.Gb=new Map;this.ec=1;this.za=!1;this.nd=0;this.pc=1;this.Uc=0;this.ce="HRTF";this.Od="inverse";this.de=600;this.be=1E4;this.fe=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Ud=this.kc=!1;this.ie=this.j.Ge();this.ka=new Map;this.Ua=new Set;this.Vd=this.$c=!1;this.dd="";this.Na=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Na&&this.Na.disconnect();this.dd=c.toLowerCase();this.Na=this.g.createMediaStreamSource(a);
this.Na.connect(Nb(this,this.dd))};this.Yb=null;self.C3Audio_GetOutputStream=()=>{this.Yb||(this.Yb=this.g.createMediaStreamDestination(),this.Wa.connect(this.Yb));return this.Yb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>pb(this,a)],["play",a=>rb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ga()}],["stop-all",()=>{for(const a of this.H)a.Ga()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ob():d.Pb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>wb(this,a)],["set-master-volume",a=>{this.ec=a.vol;this.Wa.gain.value=this.ec}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Tb(d,a)}],["set-silent",a=>{this.za=a.isSilent;this.j.Qb(this.za);for(const c of this.H)c.Wb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.Cc(a)}],["set-playback-rate",a=>yb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),vb(d,a)}],["seek",a=>zb(this,a)],["preload",a=>Ab(this,a)],["unload",a=>Bb(this,a)],["unload-all",()=>{for(const a of this.ja)a.l();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Dc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Cb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Eb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ka.delete(a);Db(this,a)}}],["tick",a=>{this.pc=a.timeScale;this.Uc=a.gameTime;this.$d=a.tickCount;if(0!==this.nd)for(var c of this.H)c.Ja();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&ub(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Fb(this,a)],["offline-render-audio",a=>Hb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Wa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Ob(){return this.za}Ha(b){this.j.Ha(b)}Ra(b){this.j.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.$d,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.ld,index:c.Wd,peak:c.cb,rms:c.ee,binCount:c.m.frequencyBinCount,freqBins:c.Td}))});0===a.length&&0===this.Ua.size&&this.$b&&(this.j.Id(this.je),this.$b=!1)}static Le(b){return b*ob}static xd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Je(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ba.xa(self.jb);"use strict";function Kb(b){b.cc||(b.cc=b.Ic());return b.cc}self.ud=class{constructor(b,a,c,d,e){this.v=b;this.pf=a;this.Oa=c;this.T=d;this.lf=e;this.Qc="";this.cc=null}l(){this.cc=this.v=null}Ic(){}V(){return this.v.V()}yc(){return this.pf}lb(){return this.Oa}xc(){return this.T}Fa(){return this.lf}ga(){}};"use strict";
self.ze=class extends self.ud{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Qc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Oa}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}l(){Qb(this.v,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Ic(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Oa})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Ub(b){if(b.Ka)return b.Ka;var a=b.v.j;if("cordova"===a.u&&a.Ad(b.Oa)&&a.ac)b.Ka=await a.Lb(b.Oa);else{a=await fetch(b.Oa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ka=await a.arrayBuffer()}}async function Vb(b){if(b.ia)return b.ia;b.ia=await Pb(b.v,b.Ka,b.nf);b.Ka=null}
self.Be=class extends self.ud{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Qc="webaudio";this.ia=this.Ka=null;this.nf=!!f}l(){Qb(this.v,this);this.ia=this.Ka=null;super.l()}async Ic(){try{await Ub(this),await Vb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Oa}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Wb=0;
function Q(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ce,b.F.distanceModel=b.v.Od,b.F.refDistance=b.v.de,b.F.maxDistance=b.v.be,b.F.rolloffFactor=b.v.fe),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function R(b,a){a=!!a;b.bc!==a&&(b.bc=a,b.bc?(Q(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.fa())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.fa())))}function vb(b,a){b.bc&&b.kd!==a&&(b.da.pan.value=a,b.kd=a)}function U(b,a){b.Pa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.zc()}function Tb(b,a){a=!!a;b.ya!==a&&(b.ya=a,b.Wb())}
function ub(b,a,c,d,e){if(b.yb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.ad?b.v.Uc:performance.now()/1E3}
self.vd=class{constructor(b,a,c){this.v=b;this.P=a;this.oa=c;this.Xb=Wb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.yb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ua=[0,0,0];this.da=null;this.bc=!1;this.kd=0;this.I=!0;this.Y=this.va=this.J=!1;this.Pa=1;this.ya=!1;this.ma=1;b=this.v.nd;this.ad=1===b&&!this.Fa()||2===b;this.Ya=this.sa=-1;this.he=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Nb(this.v,0<this.oa.length?this.oa[0]:"")}yc(){return this.P.yc()}lb(){return this.P.lb()}xc(){return this.P.xc()}Fa(){return this.P.Fa()}O(){}tc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}ga(){return this.P.ga()}Play(){}Ga(){}ob(){}Pb(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.he&&this.Ga(),Rb(this.v,"fade-ended",this.oa,this.Xb))}zc(){const b=this.Pa;return isFinite(b)?b:0}Ob(){return this.v.Ob()}Wb(){}Cc(){}Ja(){}Bc(){}Dc(){}Ac(){}kb(){var b=
this.Xb,a=this.oa,c=this.ga(),d=-1===this.Ya?this.Pa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.ma,uid:this.sa,bufferOriginalUrl:this.yc(),bufferUrl:"",bufferType:this.xc(),isMusic:this.Fa(),isLooping:this.Y,isMuted:this.ya,resumePosition:this.Ac(),pan:f,stereoPan:this.da?
this.kd:null}}Jc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ja());Tb(this,b.isMuted)}};"use strict";
self.Ae=class extends self.vd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Lc()}l(){this.Ga();this.P.Fb.disconnect();super.l()}W(){return this.P.W()}Lc(){this.I=!0;this.sa=-1;Rb(this.v,"ended",this.oa,this.Xb)}O(){return this.W().ended}tc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ya=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Ha(d);this.J=this.I=!1;this.Y=b;this.ma=1}Ga(){const b=this.W();b.paused||b.pause();this.v.Ra(b);this.I=!0;this.J=!1;this.sa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ra(b);this.J=!0}}Pb(){!this.J||this.I||this.O()||(this.v.Ha(this.W()),this.J=!1)}Wb(){this.W().muted=this.ya||this.Ob()}Cc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ja(){let b=this.ma;this.ad&&(b*=this.v.pc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Bc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Ac(){return this.Qa()}Dc(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.v.Ha(this.W()),this.va=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.Ce=class extends self.vd{constructor(b,a,c){super(b,a,c);this.s=null;this.hc=d=>this.Lc(d);this.Wc=!0;this.qb=null;this.S=this.jc=this.lc=0;this.fd=1}l(){this.Ga();W(this);this.hc=null;super.l()}Lc(b){this.J||this.va||b.target!==this.qb||(this.I=this.Wc=!0,this.sa=-1,W(this),Rb(this.v,"ended",this.oa,this.Xb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Wc}tc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.jc+(V(this)-this.lc)*this.ma;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.ya=!1;this.fd=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.hc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Wc=!1;this.Y=b;this.ma=1;this.lc=V(this);this.jc=c}Ga(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Pb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.hc,this.s.loop=this.Y,U(this,this.Pa),this.Ja(),this.s.start(0,this.S),this.lc=V(this),this.jc=this.S,this.J=!1)}zc(){return super.zc()*this.fd}Wb(){this.fd=this.ya||this.Ob()?0:1;U(this,this.Pa)}Cc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ja(){let b=this.ma;this.ad&&(b*=this.v.pc);this.s&&(this.s.playbackRate.value=b)}Bc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Pb()))}Ac(){return this.S}Dc(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Qa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.va=!1:this.va&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.hc,this.s.loop=this.Y,U(this,this.Pa),this.Ja(),this.s.start(0,this.S),this.lc=V(this),this.jc=this.S,this.va=!1)}Jc(b){super.Jc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Wd=-1;this.T=this.ld="";this.o=null}l(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.ld,params:this.o}}}
self.se=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Db=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ub=X(this);this.ub.gain.value=c;this.A.connect(this.Db);this.A.connect(this.h);this.Db.connect(this.i);this.Db.connect(this.X);this.X.connect(this.ub);this.ub.connect(this.Db)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.ub.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.xd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.ub.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Nd=this.Md="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.tb=this.g.createConvolver();this.tb.normalize=c;this.tb.buffer=a;this.A.connect(this.tb);this.A.connect(this.h);this.tb.connect(this.i)}l(){this.A.disconnect();this.tb.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Md;b.bufferUrl="";b.bufferType=this.Nd;return b}};
self.te=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.ve=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.ue=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.xd;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.xe=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.ye=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.we=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Ib=X(this);this.Ib.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Ib.gain);this.C.start(0);this.A.connect(this.Ib);this.A.connect(this.h);this.Ib.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Ib.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.re=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.nc=X(this);this.mc=X(this);b=d;.01>b&&(b=.01);this.nc.gain.value=b;this.mc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.qc=this.g.createWaveShaper();this.Rc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Rc[32768+e]=f,this.Rc[32768-
e-1]=-f;this.qc.curve=this.Rc;this.A.connect(this.nc);this.A.connect(this.h);this.nc.connect(this.qc);this.qc.connect(this.mc);this.mc.connect(this.i)}l(){this.A.disconnect();this.nc.disconnect();this.qc.disconnect();this.mc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.oe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.ne=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Td=new Float32Array(this.m.frequencyBinCount);this.ge=new Uint8Array(a);this.ee=this.cb=0;b=this.v;b.Ua.add(this);T(b)}l(){this.v.Ua.delete(this);this.m.disconnect();super.l()}Sa(){this.m.getFloatFrequencyData(this.Td);this.m.getByteTimeDomainData(this.ge);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ge[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Je;this.cb=c(this.cb);this.ee=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";function Xb(){}function Yb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function Zb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ba.xa(class extends self.Ea{constructor(b){super(b,"browser");this.u="";r(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Yb(this)],["alert",a=>this.Kc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Mc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Zb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.j.pa()?window.open(c,"_blank"):this.Gf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.pa()||"macos-wkwebview"===this.u)self.ba.Vb(!0),this.j.Ia({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Xb)}}],["exit-fullscreen",()=>{if(this.j.pa()||"macos-wkwebview"===this.u)self.ba.Vb(!1),this.j.Ia({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Xb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Kc(b){alert(b.message)}Mc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():
null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
