const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Behaviors.LOS,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.HTMLElement,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.ScriptsInEvents.EventSheet1_Event2,
		C3.ScriptsInEvents.EventSheet1_Event3,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.HTMLElement.Acts.SetPos,
		C3.Plugins.HTMLElement.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Shape3D.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Acts.RotateClockwise,
		C3.Plugins.HTMLElement.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Every,
		C3.ScriptsInEvents.EventSheet1_Event19,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Exps.QueryParam,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Car: 0},
	{LineOfSight: 0},
	{Player: 0},
	{TiledBackground: 0},
	{WallDefault: 0},
	{"3DCamera": 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Solid: 0},
	{TableDefault: 0},
	{TapeProductObject: 0},
	{TapeCollision_1: 0},
	{ButtonUp: 0},
	{ButtonDown: 0},
	{Touch: 0},
	{DistanceChecker: 0},
	{ProductData: 0},
	{CheckoutScript: 0},
	{styles: 0},
	{Cart: 0},
	{BigFloor: 0},
	{TapeProductObject2: 0},
	{TapeFrontImage2: 0},
	{TapeSideImage2: 0},
	{TapeBackImage2: 0},
	{ButtonRight: 0},
	{ButtonLeft: 0},
	{TapeBackImage1: 0},
	{TapeSideImage1: 0},
	{TapeFrontImage1: 0},
	{WindowsDefault: 0},
	{Ceiling: 0},
	{Text: 0},
	{Browser: 0},
	{PurchaseSuccessModal: 0},
	{PurchaseModalText: 0},
	{FrontWall: 0},
	{solid: 0},
	{WindowsDefault_2: 0},
	{roof: 0},
	{"3DShape5": 0},
	{Sprite: 0},
	{"3DShape4": 0},
	{DEVICE: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	WallDefault: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TableDefault: class extends self.I3DShapeInstance {},
	TapeProductObject: class extends self.I3DShapeInstance {},
	TapeCollision_1: class extends self.I3DShapeInstance {},
	ButtonUp: class extends self.ISpriteInstance {},
	ButtonDown: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	DistanceChecker: class extends self.ISpriteInstance {},
	ProductData: class extends self.IHTMLElementInstance {},
	CheckoutScript: class extends self.IHTMLElementInstance {},
	styles: class extends self.IHTMLElementInstance {},
	Cart: class extends self.IHTMLElementInstance {},
	BigFloor: class extends self.ISpriteInstance {},
	TapeProductObject2: class extends self.I3DShapeInstance {},
	TapeFrontImage2: class extends self.ISpriteInstance {},
	TapeSideImage2: class extends self.ISpriteInstance {},
	TapeBackImage2: class extends self.ISpriteInstance {},
	ButtonRight: class extends self.ISpriteInstance {},
	ButtonLeft: class extends self.ISpriteInstance {},
	TapeBackImage1: class extends self.ISpriteInstance {},
	TapeSideImage1: class extends self.ISpriteInstance {},
	TapeFrontImage1: class extends self.ISpriteInstance {},
	WindowsDefault: class extends self.I3DShapeInstance {},
	Ceiling: class extends self.I3DShapeInstance {},
	Text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	PurchaseSuccessModal: class extends self.ISpriteInstance {},
	PurchaseModalText: class extends self.ITextInstance {},
	FrontWall: class extends self.I3DShapeInstance {},
	solid: class extends self.ISpriteInstance {},
	WindowsDefault_2: class extends self.I3DShapeInstance {},
	roof: class extends self.I3DShapeInstance {},
	_3DShape5: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_3DShape4: class extends self.I3DShapeInstance {}
}