const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.JavaScriptInEvents.EventSheet1_Event3,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Shape3D.Acts.SetPosToObject,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Mouse.Cnds.HasPointerLock,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{Player: 0},
	{Solid: 0},
	{WallObject: 0},
	{"3DCamera": 0},
	{Keyboard: 0},
	{RoomType: 0},
	{RoomCreator: 0},
	{DoorObject: 0},
	{Audio: 0},
	{Mouse: 0},
	{DoorLeft: 0},
	{DoorRight: 0},
	{DebugText: 0},
	{InitialOverlay: 0},
	{Bullet: 0},
	{PlayerProjectile: 0},
	{ProjectileObject: 0},
	{CooldownBar: 0},
	{PortalObject: 0},
	{RotatingTrap_1: 0},
	{RotatingTrapObject: 0},
	{PortalFrame: 0},
	{RotatingTrapBlade: 0},
	{RotatingBladeObject: 0},
	{HealthBar: 0},
	{BoxObject: 0},
	{Sprite: 0},
	{JunkSpawn: 0},
	{ShootingCooldown: 0},
	{Health: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	WallObject: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	RoomCreator: class extends self.ISpriteInstance {},
	DoorObject: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	DoorLeft: class extends self.I3DShapeInstance {},
	DoorRight: class extends self.I3DShapeInstance {},
	DebugText: class extends self.ITextInstance {},
	InitialOverlay: class extends self.ISpriteInstance {},
	PlayerProjectile: class extends self.ISpriteInstance {},
	ProjectileObject: class extends self.I3DShapeInstance {},
	CooldownBar: class extends self.ISpriteInstance {},
	PortalObject: class extends self.ISpriteInstance {},
	RotatingTrap_1: class extends self.ISpriteInstance {},
	RotatingTrapObject: class extends self.I3DShapeInstance {},
	PortalFrame: class extends self.I3DShapeInstance {},
	RotatingTrapBlade: class extends self.ISpriteInstance {},
	RotatingBladeObject: class extends self.I3DShapeInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	BoxObject: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	JunkSpawn: class extends self.ISpriteInstance {}
}