const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.EventSheet1_Event3,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Shape3D.Acts.SetPosToObject,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Shape3D.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.HasPointerLock,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Shape3D.Cnds.IsVisible,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.Shape3D.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Camera3D.Acts.MoveAlongLayoutAxis,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{Player: 0},
	{Solid: 0},
	{WallObject: 0},
	{"3DCamera": 0},
	{Keyboard: 0},
	{RoomType: 0},
	{RoomCreator: 0},
	{DoorObject: 0},
	{Audio: 0},
	{Mouse: 0},
	{DoorLeft: 0},
	{DoorRight: 0},
	{Bullet: 0},
	{PlayerProjectile: 0},
	{ProjectileObject: 0},
	{PortalObject: 0},
	{PortalFrame: 0},
	{BoxObject: 0},
	{JunkSpawn: 0},
	{FloorBackground: 0},
	{Health: 0},
	{Damage: 0},
	{BatCollision: 0},
	{BatObject: 0},
	{BatAnimations: 0},
	{Sky: 0},
	{HealthBar: 0},
	{HealthBarBorder: 0},
	{ScreenOverlay: 0},
	{GameOverTitle: 0},
	{GameOverText: 0},
	{DeadEnemyObject: 0},
	{DeadEnemiesAnimation: 0},
	{FloorText: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{UIBorder: 0},
	{UICorners: 0},
	{EnemySpawnerOrb: 0},
	{CoinObject: 0},
	{EnemySpawner: 0},
	{SmallSolidBlock: 0},
	{SpawnerInsideObject: 0},
	{Sprite3: 0},
	{EnemySpawnerConnector: 0},
	{Walls: 0},
	{Enemies: 0},
	{ShootingCooldown: 0},
	{CurrentHealth: 0},
	{CurrentFloor: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	WallObject: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	RoomCreator: class extends self.ISpriteInstance {},
	DoorObject: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	DoorLeft: class extends self.I3DShapeInstance {},
	DoorRight: class extends self.I3DShapeInstance {},
	PlayerProjectile: class extends self.ISpriteInstance {},
	ProjectileObject: class extends self.I3DShapeInstance {},
	PortalObject: class extends self.ISpriteInstance {},
	PortalFrame: class extends self.I3DShapeInstance {},
	BoxObject: class extends self.I3DShapeInstance {},
	JunkSpawn: class extends self.ISpriteInstance {},
	FloorBackground: class extends self.ITiledBackgroundInstance {},
	BatCollision: class extends self.ISpriteInstance {},
	BatObject: class extends self.I3DShapeInstance {},
	BatAnimations: class extends self.ISpriteInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	HealthBarBorder: class extends self.ISpriteInstance {},
	ScreenOverlay: class extends self.ISpriteInstance {},
	GameOverTitle: class extends self.ITextInstance {},
	GameOverText: class extends self.ITextInstance {},
	DeadEnemyObject: class extends self.I3DShapeInstance {},
	DeadEnemiesAnimation: class extends self.ISpriteInstance {},
	FloorText: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	UIBorder: class extends self.ITiledBackgroundInstance {},
	UICorners: class extends self.ISpriteInstance {},
	EnemySpawnerOrb: class extends self.I3DShapeInstance {},
	CoinObject: class extends self.I3DShapeInstance {},
	EnemySpawner: class extends self.I3DShapeInstance {},
	SmallSolidBlock: class extends self.ISpriteInstance {},
	SpawnerInsideObject: class extends self.I3DShapeInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	EnemySpawnerConnector: class extends self.ISpriteInstance {},
	Walls: class extends self.I3DShapeInstance {},
	Enemies: class extends self.ISpriteInstance {}
}